baseURL = "https://zhoucaiqi.com/"
languageCode = "zh-cn"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "团队"
  URL = "#about"
  weight = 2

#  [[menu.header]]
#  name = "客户"
#  URL = "#portfolio"
#  weight = 3

  [[menu.header]]
  name = "联系"
  URL = "#contact"
  weight = 4


#  [[menu.footer]]
#  name = "团队"
#  URL = "#about"
#  weight = 2

#  [[menu.footer]]
#  name = "客户"
#  URL = "#portfolio"
#  weight = 3

#  [[menu.footer]]
#  name = "联系"
#  URL = "#contact"
#  weight = 4

  [[menu.footer]]
  name = "粤ICP备15022820号"
  URL = "https://beian.miit.gov.cn/"
  weight = 4


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Choicky ZHOU"
    text2 = ""

  [params.footer]
      copyright = "© Choicky. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
